version: "3.8"
services:
  client:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - /Users/yogesh/projects/replnotes/replnotes:/app
    env_file:
      - .env
