version: "3.8"
services:
  #   Run the node application
  replnotes:
    container_name: replnotes
    restart: unless-stopped
    env_file:
      - replnotes/.env.staging.local
    environment:
      - NODE_ENV=production
    build:
      context: replnotes

  # Run the caddy server
  caddy:
    image: caddy/caddy:2.4.3-alpine
    container_name: caddy-service
    restart: unless-stopped
    environment:
      - ACME_AGREE=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
